spring.application.name=statistic_api
server.port=8282

spring.datasource.url=jdbc:postgresql://localhost:5430/statistic_api
spring.datasource.username=statistic_api_user
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/migration/db.changelog-1.0-init.yaml
spring.liquibase.enabled=true
spring.liquibase.user=statistic_api_user
spring.liquibase.password=123
spring.liquibase.default-schema=public